from typing import Protocol

class Sentence(Protocol):
    @classmethod
    def mempty(self): ...
    def combine(self, other): ...
    def __len__(self): ...
    def __getitem__(self, index: int): ...
